  on:
    workflow_call:

  jobs:
    docker-build-push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: testing task
          if: contains(github.repository, 'actions')
          run: |
            echo "This step runs only if repository name contains 'actions'"

        # - name: Download artifact
        #   if: contains(github.repository, 'actions')
        #   uses: actions/download-artifact@v2
        #   with:
        #       name: shared-data

        - name: Read environment file and set environment variables
          run: |
            source prejob-vars.txt
            ENV_FILE=".github/workflows/$environment_type-vars.env"
            cat $ENV_FILE >> $GITHUB_ENV
            echo "Loaded $ENV_FILE into environment variables"

        - name: Docker Build and Push
          run: |
            CONTAINER_IMAGE_NAME=$ACR_REGISTRY/$IMAGE_NAME:${{ github.run_id }}
    
            # Docker Log in to Azure Container Registry (ACR)
            echo "docker login -u $ACR_USERNAME -p ${{ secrets.ACR_PASSWORD }} $ACR_REGISTRY"
    
            # Build the Docker image
            echo "docker build -t $CONTAINER_IMAGE_NAME ."
    
            # Push Docker Image to ACR
            echo "docker push $CONTAINER_IMAGE_NAME"

            echo "successfully pushed $CONTAINER_IMAGE_NAME"
