name: Python Jobs

on:
  workflow_call:

jobs:
  python-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version you want to use

      - name: Create and Activate Virtual Environment
        run: |
            echo "create venv"
        #   python -m venv venv
        #   source venv/bin/activate

      - name: Install Dependencies
        run: echo "pip install -r requirements.txt"

      - name: Run Python Script
        run: echo "python manage.py"  # Replace 'your_script.py' with the name of your Python script
