name: setup environment

on:
  workflow_call:
    outputs:
        environment:
            description: "Get variables files dynamically based on commit branch"
            value:  ${{ jobs.pre-job.outputs.environment_type }}

jobs:
  pre-job:
    runs-on: ubuntu-latest
    outputs:
        environment_type: ${{ steps.set_env.outputs.environment }}
    steps:
      - name: Set environment based on branch name
        id: set_env
        run: |
          if [[ ${{ github.ref }} == "refs/heads/dev" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} == "refs/heads/qa" ]]; then
            echo "environment=qa" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} == "refs/heads/master" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          else
            echo "environment=unknown environment" >> $GITHUB_OUTPUT
          fi

          echo "Environment: $environment"
          cat $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Environment
        run: |
          echo "Environment: $environment"