name: setup environment

on:
  workflow_call:
    outputs:
        environment:
            description: "Get variables files dynamically based on commit branch"
            value:  ${{ jobs.pre-job.outputs.environment_type }}

jobs:
  pre-job:
    runs-on: ubuntu-latest
    outputs:
        environment_type: ${{ steps.set_env.outputs.environment }}
    steps:
      - name: Set environment based on branch name
        id: set_env
        run: |
          if [[ ${{ github.ref }} == "refs/heads/dev" ]]; then
            echo "environment_type=dev" >> prejob-vars.txt
          elif [[ ${{ github.ref }} == "refs/heads/qa" ]]; then
            echo "environment_type=qa" >> prejob-vars.txt
          elif [[ ${{ github.ref }} == "refs/heads/master" ]]; then
            echo "environment_type=prod" >> prejob-vars.txt
          else
            echo "environment_type=unknown environment" >> prejob-vars.txt
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: shared-data
          path: prejob-vars.txt