name: Reusable workflow

on:
  workflow_call:
    
jobs:
    save_variable:
      runs-on: ubuntu-latest
      steps:
        - name: Create file with variable data
          run: echo "name=navya" >> variable.txt
        
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: shared-data
            path: variable.txt
  