name: build and deploy

on:
  workflow_call:

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
            source $GITHUB_ENV
            cat $GITHUB_ENV
            echo $firstword

            #echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}