name: build and deploy

on:
  workflow_call:

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_ENV
            #echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}